/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DartBoard {
    }
}
declare global {
    interface HTMLDartBoardElement extends Components.DartBoard, HTMLStencilElement {
    }
    var HTMLDartBoardElement: {
        prototype: HTMLDartBoardElement;
        new (): HTMLDartBoardElement;
    };
    interface HTMLElementTagNameMap {
        "dart-board": HTMLDartBoardElement;
    }
}
declare namespace LocalJSX {
    interface DartBoard {
    }
    interface IntrinsicElements {
        "dart-board": DartBoard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dart-board": LocalJSX.DartBoard & JSXBase.HTMLAttributes<HTMLDartBoardElement>;
        }
    }
}
